# Generated by Django 4.2.1 on 2023-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_airport_alter_flight_destination_alter_flight_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fName", models.CharField(max_length=64)),
                ("lName", models.CharField(max_length=64)),
                (
                    "flights",
                    models.ManyToManyField(
                        blank=True, related_name="passengers", to="flights.flight"
                    ),
                ),
            ],
        ),
    ]
